### ISSUE TITLE
Is it possible to play atleast 2 videos together in a list? planning to use toro2.1

### ISSUE THREAD

**Issue by sudhasri17** [eneim/Toro#121]
Make sure to provide the following informations and check:

- [ ] Toro dependencies (Eg: ```com.github.eneim:Toro:develop-SNAPSHOT```)

- [ ] Android manifacture | product name | OS Version | rooted or clean (Eg: Sony | Z4 | 5.0 | clean)

- Logcat (if it was a fatal issue)

**Comment by eneim** [comment]
Currently no. And no support plan. I will need a strong motivation for that.

**Comment by sudhasri17** [comment]
Any direction or suggestion as i wish to implement this with toro would be great.

**Comment by eneim** [comment]
@sudhasri17 My mind set for Toro is totally focus on Single Video, so there is no such suggestion here. As said I will prefer a strong motivation for that to think further about how you can do that. If you don't mind please give me the answer for: "Why you want to do that" and "How is the expected behaviour". If it is sensitive behaviour that should not be public, you can email me anytime.

**Comment by sudhasri17** [comment]
my recyclerview contains a few dynamic videoviews of which one is like a banner, so keep that in loop always. other videos ll play as it gets visible.

**Comment by eneim** [comment]
@sudhasri17 I understand the situation, but I will not provide anything like this by the library. One suggestion is to have a separated ScrollListener, ViewHolder type for the Video Ads, **MUST NOT** implement Toro's Player interface (or else it will be filtered out), and implement some same flow with Toro.
