### ISSUE TITLE
PlayerSelector.NONE make current playing video paused when recyclerView scroll

### ISSUE THREAD

**Issue by vtproduction** [eneim/toro#263]
In your BasicListActivity, I just set the PlayerSelector to NONE and manually play/pause the video with the click on ViewHolder. However, when the recyclerView finish scroll (just a little bit, to make sure that the current playing video is fully visible), the player pause automatically.

Could you please tell me how to fix this issue ? I just want to only play video by click on it. Thanks a lot.

Here is the demo video: [https://www.youtube.com/watch?v=pNnxtHNzAaw](https://www.youtube.com/watch?v=pNnxtHNzAaw)

**Comment by eneim** [comment]
@vtproduction Currently manually start/pause the Player will not talking to Container. Which means that once you set the selector to "NONE", every Scroll will end up pausing all Players (which is expected). If you need something complicated, you may need a customized selector.

**Comment by vtproduction** [comment]
@eneim can you give me some instruction to customize it ?

**Comment by eneim** [comment]
@vtproduction Hi, this is not trivial, but can be done with the following steps:

0. I assume that you are using SimpleExoPlayerView (SEPV), because my tutorial below base on that. Using other Widget needs your own work.

1. You need to intercept in the manual play/pause trigger (i.e User click to play/pause from SEPV). To do this, you can use [this method from SEPV](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/SimpleExoPlayerView.java#L637) (which in turn asks the ``PlaybackControlView`` to set its Dispatcher). 

1'. Record the event of User clicking play/pause button. This is done by customizing the ControlDispatcher you set above, adding your own logic to remember the Item that is triggered. See my demo code below:

```java
// Prepare the default Dispatcher.
ControlDispatcher dispatcher = PlaybackControlView.DEFAULT_CONTROL_DISPATCHER;

// TODO: Put the following into onBindViewHolder(). playerView is the SimpleExoPlayerView instance.
// adapter = the Adapter that is binding this ViewHolder.
playerView.setControlDispatcher(new ControlDispatcher() {
        @Override public boolean dispatchSetPlayWhenReady(Player player, boolean playWhenReady) {
          boolean dispatched = dispatcher.dispatchSetPlayWhenReady(player, playWhenReady);
          if (dispatched) {
              adapter.manualItem.set(getPlayerOrder());
              if (!playWhenReady) adapter.manualItem.set(-1); // User is pausing, so clear the manual one.
          }
          return dispatched;
        }

        @Override public boolean dispatchSeekTo(Player player, int windowIndex, long positionMs) {
          return dispatcher.dispatchSeekTo(player, windowIndex, positionMs);
        }

        @Override public boolean dispatchSetRepeatMode(Player player, int repeatMode) {
          return dispatcher.dispatchSetRepeatMode(player, repeatMode);
        }
      });
```

The setup is done when you bind data to your ViewHolder (which is a ``ToroPlayer`` of course). Here I have a field "manualItem" in the **Adapter** which is an ``AtomicInteger`` to save the manual player order (= adapter position). (You can use a simple ``int`` of course). This value must be negative by default (because be default there is no item triggered yet). I set it to -1 by default.

The ``dispatchSetPlayWhenReady`` is called when User click to the play/pause button. I have a default dispatcher as the delegate object. Make sure you catch the boolean value returned from it, because when dispatcher's method returns false, it means that the dispatcher didn't do anything.

3. Custom the Selector so that: it behaves as ``PlayerSelector.NONE`` for all players, but allows the one that is manually triggered to act by itself. The customization can be done using some other tricks, below is one of my demo:

```java
// 1. We can use a Filter to pick the one that is manually triggered. Make sure the player wants to play too.
final Container.Filter manualPlay =
        player -> player.wantsToPlay() && player.getPlayerOrder() == adapter.manualItem.get();

// 2. Create a selector which can select only the one that is manually triggered.
PlayerSelector  selector = new PlayerSelector() {
      @NonNull @Override public Collection<ToroPlayer> select(@NonNull Container container,
          @NonNull List<ToroPlayer> items) {
        return container.filterBy(manualPlay); // This is where magic happens.
      }

      @NonNull @Override public PlayerSelector reverse() {
        return this;
      }
    };

    container.setPlayerSelector(selector); // Apply the customized NONE Selector.
```

Please try my suggestion above and tell me if it helps. I will push a demo reproducing this to master soon.

**Comment by vtproduction** [comment]
@eneim Thank you so much!  I will follow your steps and tell you soon.
'Cám ơn rất nhiều'

**Comment by vtproduction** [comment]
@eneim Your solution basically worked. Thanks again !

**Comment by eneim** [comment]
@maxbaldrighi Which version of ExoPlayer/Toro you are using. I will look into the code and see what happens.

**Comment by maxbaldrighi** [comment]
I was using the 3.5.2 version. Now I've just updated version.
Anyways, I couldn't write you before, but I basically managed to fully understand your steps.
Just to have your confirmation: the method call to intercept in SEPV you were referring to was about to manually dispatch the PLAY and PAUSE key events as the user used the controller, right?

Because, I managed to block the unwanted `onScrollChanged` trigger, but now I'm struggling because I don't want to use the player's controller.
I'm trying to find a way to subclass `PlayerView` and be able to use the controller 's events without being forced to use the property `useController`, which unfortunately forces the controller's visibility to VISIBLE if `true`.

**Comment by maxbaldrighi** [comment]
Hello @eneim, just a quick update.

So, in the end yesterday I managed to solve the controller visibility issue (and I'm gonna post later my solution for anyone who may need it).

I noticed, though, one thing of more pressing concern for this library: the whole thing seems to work perfectly with Toro 3.5.2, but NOT with the latest release.
I didn't have the chance to debug attentively what's happening, though. I hope to be able to do that during the weekend and to give you a more accurate report.

**Comment by eneim** [comment]
@maxbaldrighi Thanks so much for your information. It is definitely something wrong. I will find time to double check this.

**Comment by maxbaldrighi** [comment]
As I promised, I'm gonna start with pasting my solution for using the manual controls without using the player's controller.

Subclassing PlayerView, I just overrode this method:

    override fun dispatchMediaKeyEvent(event: KeyEvent?): Boolean {
        useController = true
        val bool = super.dispatchMediaKeyEvent(event)
        useController = false
        return bool
    }

and used this line `app:use_controller="false"` in the xml file.
Doing so, I enable the useController property, just to make sure that the default tests based on useController property pass, and the disabling it again.
From what I saw, it seems to work fine.

**Comment by maxbaldrighi** [comment]
I finally had the time to properly debug. 
During helper initialization, `ExoPlayerViewHelper.prepare(boolean)` gets called with `false` passed as argument. Then `ExoPlayable.prepare(boolean)` -> `PlayableImpl.prepare(boolean)`

Here lies the "problem" emerged because of the different implementation between the two versions of toro of `PlayableImpl.prepare(boolean)`:

**3.5.2**: no matter what value `prepareSource` argument carries `player` property is always initialized.

    @CallSuper @Override public void prepare(boolean prepareSource) {
        if (player == null) {
            player = with(checkNotNull(creator.getContext(), "ExoCreator has no Context")).requestPlayer(creator);
            if (player instanceof ToroExoPlayer && volumeChangeListeners != null) {
                for (ToroPlayer.OnVolumeChangeListener listener : volumeChangeListeners) {
                    ((ToroExoPlayer) player).addOnVolumeChangeListener(listener);
                }
            }
        }
        ...
    }

**3.6.1.2802**: if `prepareSource==false`, `player` property is not initialized, because the instantiation has been moved inside `ensureMediaSource()`.

    @CallSuper @Override public void prepare(boolean prepareSource) {
        if (prepareSource) {
            ensureMediaSource();
            ensurePlayerView();
        }
    }

So this means that if `player==null`, the methods `PlayerView.switchTargetView(Player, PlayerView, PlayerView)` and `PlayerControlView.setPlayer(Player)` carry around a `null` player instance, until the call to `PlayerControlView.dispatchMediaKeyEvent()` returns with no action performed because the test `if (player == null || ...) { ... }` fails.

Hope I explained everything clearly.
Any suggestions will be much appreciated!

**Comment by eneim** [comment]
@maxbaldrighi Thanks so much for your investigation. The change in "when Player instance is created" is a correct found. And at the time I wrote it, it is by intended. The reason is: the flag in "prepare" method suggests client that it can initialize playback resource lazily, which save some frame from dropping. This was half done in 3.5.2, the Player instance is created there, which in turns, init other resources like Renderers. Case by case, this take up to 20ms which will produce bad UX in first scroll. As a result, I also make the Player initialization to be lazy as well, and just create it for the first time when it is requested.

The reason above, doesn't take into account what you found today. I will think about this scenario carefully and will reply here as soon as I have some idea.

**Comment by maxbaldrighi** [comment]
Perfect, thanks!

Looking forward to it!

**Comment by maxbaldrighi** [comment]
Hello @eneim !
Any ETA about the issue we were talking about a few weeks ago?
Or do you have any temporary workaround in mind?

Thanks in advance!

**Comment by eneim** [comment]
Hi @maxbaldrighi , sorry for the wait. Can you try the 3.7.0.2901-SNAPSHOT and see if it helps. In this update I change some internal mechanism that include the place where ExoPlayer instance is created. This way, the Dispatcher will be dispatched correctly.

Please follow this code [link](https://github.com/eneim/toro/blob/nam/v3/370-r2901/app/src/main/java/im/ene/toro/sample/basic/BasicPlayerViewHolder.java#L78) to start using this new mechanism. (Underline classes are all updated, so I need some time to document them out as a proper changelog, and further performance test).

This requires ExoPlayer 2.9.1, so let me know if it doesn't work for you.

**Comment by maxbaldrighi** [comment]
Thank you very much for your hard work.
I am very busy at work, right now, but as soon as I can try it, I will
report the results to you!

Massimo

**Comment by manishh776** [comment]
@maxbaldrighi Can you post the solution to this issue if you found it. Thanks in advance.
