### ISSUE TITLE
ToroPlayer EventListener callbacks sequence

### ISSUE THREAD

**Issue by DummyCo** [eneim/toro#304]
Hi, @eneim.
Looks like _ExoPlayer 2.6.1 / Toro 3.4.0-A1_ introduced some changes to mentioned callbacks sequence or is it some kind of artifact we're getting with caching?
New sequence:

12:54:09.396 onPlaying() called
12:54:09.452 onBuffering() called
12:54:09.916 onPlaying() called

The problem is first _onPlaying()_ has nothing to show except the black screen actually and _onBuffering()_ is called after it. I'm binding my loaders & placeholders logic to these events and seems like recent updates are forcing me to check both _onBuffering()_ and _onPlaying()_ firing count to make decisions.
Is it intended behavior now?
Thank you!

**Comment by eneim** [comment]
@DummyCo Good catch. What I found is a bit long, but hope it is clear enough. I made a quick debug on this case, part of the log as below:

```
[Cold start (start from nothing)]
I/ToroExo:Basic: Player#play()
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [1]
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [2]
W/ToroExo:Basic: onBuffering: 94
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [3]
D/ToroExo:Basic: onPlaying: 3866
I/ToroExo:Basic: Player#pause()
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [false], playbackState = [3]
D/ToroExo:Basic: onPaused

[Warm start (when in Cold started state, press Back button, and then open the App again)]
I/ToroExo:Basic: Player#play()
**D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [3]** <-- Old State is not reset ...
D/ToroExo:Basic: onPlaying: 15
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [2]
W/ToroExo:Basic: onBuffering: 67 <-- just 67 ms after the call, it starts buffering as expected.
D/ToroExo:Helper: onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [3]
D/ToroExo:Basic: onPlaying: 966 <-- first buffering done, actual playback could start.
```

(The number comes after the method call says 「how many milliseconds are there from now-the time this method is called-to the event before it」).

I also annotate how the app is started. When you do the Cold start, everything starts from zero, so it starts from ``onBuffering`` as expected.

When you press Back button, the Activity is destroyed, but the Application is still there waiting for either a restart or a system swipe. In this case, I click the icon to restart it right away (Warm start). What you have now is: the SimpleExoPlayer instances are still in the Player pool (which is expected), so when your Views are back, it get the one used before whose **latest state is STATE_READY**.

So your first call to play() will see the Player start from that State, and a blink after that (few millisecond), it starts buffering due to the actual behavior.

So it is expected with current implementation, but may not what we want at the end. Let me see if there is a certain way to "reset" the Player instance state to IDLE after releasing the Helper.

**Comment by eneim** [comment]
@DummyCo Turn out ``stop()`` does the job. Will be in Alpha 2 soon :D.

**Comment by DummyCo** [comment]
@eneim in case _ViewHolders_ are reused among the _RecyclerView_ I assume the same problem spawns when  player with **STATE_READY** from one item is passed to another one, right?

**Comment by eneim** [comment]
@DummyCo Sadly yes, the only way to reset the Player is to do it or recreate it (sounds obvious, but now I forgot to call it so ...). Player instance has no idea about which RecyclerView is using it (or actually the ViewHolder), so when you pass it around, it will be Ready at first (except for the very first time it is created).

Current implementation of Playable interface doesn't allow you to extend or customize it, I will put more flexibility in next release as well.

**Comment by eneim** [comment]
@DummyCo Just figured out one point that current implementation may not good for cross-RecyclerView reusability. 

Saying your ViewHolder is having a Helper initialized, it will hold an instance of "Container" which is the RecyclerView using the ViewHolder. Because this Helper is released only when the Container detaches the ViewHolder, or the Container is detached from Window, or the Activity is stopped and ``onSaveInstanceState`` is called, or you scroll the Screen that make the ViewHolder be hidden.

The worst case is, those operations above could not happen, but because the ViewHolder is shared between RVs (saying you have 2 RV on screen, sharing the same RecyclerViewPool), there is a chance that the not-released Helper is reused in other Container --> this is bad.

I have not reproduce this, but I could imagine the risk. Also the fix is on my code already. It will remove the dependency of Container from ToroPlayerHelper, as well as ExoPlayerViewHelper, making the Helper to only depend on the ToroPlayer, which is safe, and reusable.

If you found this issue too, please be patient as you are covered, and the update will be there in next release ;).

**Comment by DummyCo** [comment]
Seems like it's safe to close now
