### ISSUE TITLE
How to scroll the container?

### ISSUE THREAD

**Issue by vsevolod-sp** [eneim/toro#447]
Default methods
`container.scrollToPosition(0);`
 `container.smoothScrollToPosition(0);`
is not work

**Comment by eneim** [comment]
@vsevolod-sp What do you want to do? Scroll it to specific position? What is your LayoutManager? When you call the method?

**Comment by vsevolod-sp** [comment]
@eneim 

My xml struct:
```
<RelativeLayout>

    <CoordinatorLayout>

        <AppBarLayout />

        <RelativeLayout>
            <im.ene.toro.widget.Container />
            <LinearLayout />
        </RelativeLayout>

    </CoordinatorLayout>

    <LinearLayout />

</RelativeLayout>
```

Container setup
```
container = getView().findViewById(R.id.containerToro);
container.setLayoutManager(new LinearLayoutManager(getContext()));
container.setAdapter(adapter);
```

**Comment by eneim** [comment]
@vsevolod-sp Does it work if you replace the Container by a normal RecyclerView? Can you share the code where you call the method?

-- For your information, if you call container.scrollToPosition(pos) right after setting the Adapter or LayoutManager, it may not work, because the RecyclerView need to be laid out first. You can try to put the call inside a block like this:

```java
container.post(() -> {
    container.scrollToPosition(0);
})
```

**Comment by vsevolod-sp** [comment]
@thiagoricieri It worked, thank you!
