### ISSUE TITLE
v2 release date

### ISSUE THREAD

**Issue by EligijusStarinskas** [eneim/Toro#78]
Hey, realy nice library!!

Do you know when v2 will be released? Can't wait to try it out 👍

**Comment by eneim** [comment]
Hi there, thanks for the interest. Actually this release is quite late since I have many thing to do. I may not be at good condition until the 3rd week of August, to FYI.

v2.0 will be taken a better care right after that, and I will try to release it at the end of August. Right now RC5 is safe to try, just need some tutorial :-s, but you are encouraged to see sample code first.

**Comment by EligijusStarinskas** [comment]
Cool, I will try it, thanks !
